# Generated by Django 6.0.6 on 2026-07-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usermodel_manually_rename_name_usermodel_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel_manually',
            old_name='username',
            new_name='name',
        ),
    ]
