# Generated by Django 6.0.6 on 2026-07-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_usermodel_manually_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('bio', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
