# Generated by Django 6.0.6 on 2026-07-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={},
        ),
    ]
