# Generated by Django 6.0.6 on 2026-07-08 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='postmodel',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.profilemodel'),
        ),
    ]
