# Generated by Django 6.0.6 on 2026-07-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_postmodel_options_alter_profilemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.ManyToManyField(to='content.tagmodel'),
        ),
    ]
