# Generated by Django 6.0.6 on 2026-07-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
