# Generated by Django 6.0.6 on 2026-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_followmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
